# Generated by tools/generate_protocol.py — do not edit
# Source: elysium/invoke.xml
import struct

class PacketType:
    HANDSHAKE_REQUEST  = 0x01
    HANDSHAKE_RESPONSE = 0x02
    ENTITY_SPAWN       = 0x10
    ENTITY_DESPAWN     = 0x11
    ENTITY_UPDATED     = 0x20
    INVOKE_REQUEST     = 0x40
    INVOKE_RESPONSE    = 0x41

PROTOCOL_VERSION = 1

_PACKET_HEADER_FMT = '<BBHI'
_INVOKE_HEADER_FMT = '<IHH'

PACKET_HEADER_SIZE = struct.calcsize(_PACKET_HEADER_FMT)  # 8
INVOKE_HEADER_SIZE = struct.calcsize(_INVOKE_HEADER_FMT)  # 8


class PacketHeader:
    def __init__(self, packet_type: int, payload_size: int, 
                 flags: int = 0, tick: int = 0):
        self.packet_type  = packet_type
        self.flags        = flags
        self.payload_size = payload_size
        self.tick         = tick

    def to_bytes(self) -> bytes:
        return struct.pack(_PACKET_HEADER_FMT,
            self.packet_type, self.flags, self.payload_size, self.tick)

    @staticmethod
    def from_bytes(data: bytes, offset: int = 0) -> 'PacketHeader':
        packet_type, flags, payload_size, tick = struct.unpack_from(
            _PACKET_HEADER_FMT, data, offset)
        return PacketHeader(packet_type, payload_size, flags, tick)


class InvokeHeader:
    def __init__(self, invoke_id: int, procedure_id: int, payload_size: int = 0):
        self.invoke_id    = invoke_id
        self.procedure_id = procedure_id
        self.payload_size = payload_size

    def to_bytes(self) -> bytes:
        return struct.pack(_INVOKE_HEADER_FMT,
            self.invoke_id, self.procedure_id, self.payload_size)

    @staticmethod
    def from_bytes(data: bytes, offset: int = PACKET_HEADER_SIZE) -> 'InvokeHeader':
        invoke_id, procedure_id, payload_size = struct.unpack_from(
            _INVOKE_HEADER_FMT, data, offset)
        return InvokeHeader(invoke_id, procedure_id, payload_size)


class InvokeRequest:
    """Builds a complete invoke request packet ready to send."""
    def __init__(self, invoke_id: int, procedure_id: int, 
                 payload: bytes, tick: int = 0):
        self.invoke_id    = invoke_id
        self.procedure_id = procedure_id
        self.payload      = payload
        self.tick         = tick

    def to_bytes(self) -> bytes:
        invoke_hdr = InvokeHeader(
            self.invoke_id, self.procedure_id, len(self.payload)).to_bytes()
        full_payload = invoke_hdr + self.payload
        pkt_hdr = PacketHeader(
            PacketType.INVOKE_REQUEST, len(full_payload), tick=self.tick).to_bytes()
        return pkt_hdr + full_payload


class InvokeResponse:
    """Parsed invoke response received from the server."""
    def __init__(self, packet_header: PacketHeader, 
                 invoke_header: InvokeHeader, payload: bytes):
        self.packet_header = packet_header
        self.invoke_header = invoke_header
        self.payload       = payload

    @staticmethod
    def from_bytes(data: bytes) -> 'InvokeResponse':
        pkt_hdr    = PacketHeader.from_bytes(data)
        invoke_hdr = InvokeHeader.from_bytes(data)
        payload    = data[PACKET_HEADER_SIZE + INVOKE_HEADER_SIZE:]
        return InvokeResponse(pkt_hdr, invoke_hdr, payload)

class ProcedureId:
    PING = 0xff
    SPAWNPLAYER = 0x1



class PingRequest:
    def __init__(self, client_tick: int = 0):
        self.client_tick = client_tick

    def to_bytes(self) -> bytes:
        return struct.pack('<I', self.client_tick)

    @staticmethod
    def from_bytes(data: bytes, offset: int = 0) -> 'PingRequest':
        client_tick, = struct.unpack_from('<I', data, offset)
        return PingRequest(client_tick)


class PingResponse:
    def __init__(self, server_tick: int = 0, echo_client_tick: int = 0):
        self.server_tick = server_tick
        self.echo_client_tick = echo_client_tick

    def to_bytes(self) -> bytes:
        return struct.pack('<II', self.server_tick, self.echo_client_tick)

    @staticmethod
    def from_bytes(data: bytes, offset: int = 0) -> 'PingResponse':
        server_tick, echo_client_tick, = struct.unpack_from('<II', data, offset)
        return PingResponse(server_tick, echo_client_tick)


class SpawnPlayerRequest:
    def __init__(self, scene_id: int = 0, player_name: str = ''):
        self.scene_id = scene_id
        self.player_name = player_name

    def to_bytes(self) -> bytes:
        out = b''
        out += struct.pack('<I', self.scene_id)
        _b = self.player_name.encode('utf-8')
        out += struct.pack('<H', len(_b)) + _b
        return out

    @staticmethod
    def from_bytes(data: bytes, offset: int = 0) -> 'SpawnPlayerRequest':
        pos = offset
        obj = SpawnPlayerRequest()
        obj.scene_id = struct.unpack_from('<I', data, pos)[0]; pos += 4
        _len, = struct.unpack_from('<H', data, pos); pos += 2
        obj.player_name = data[pos:pos+_len].decode('utf-8'); pos += _len
        return obj


class SpawnPlayerResponse:
    def __init__(self, entity_id: int = 0, success: bool = False):
        self.entity_id = entity_id
        self.success = success

    def to_bytes(self) -> bytes:
        return struct.pack('<IB', self.entity_id, int(self.success))

    @staticmethod
    def from_bytes(data: bytes, offset: int = 0) -> 'SpawnPlayerResponse':
        entity_id, success, = struct.unpack_from('<IB', data, offset)
        success = bool(success)
        return SpawnPlayerResponse(entity_id, success)
