// Generated by eidc — do not edit
// Source: Invoke.xml
#pragma once
#include "Core/Serial.h"
#include "Services/InvokeService.h"

namespace Elysium::Generated {

struct PingRequest {
    uint32_t clientTick = 0;

    static void Write(const PingRequest& self, SerialBuffer& buf) {
        buf.WriteU32(self.clientTick);
    }

    static void Read(PingRequest& self, SerialBuffer& buf) {
        self.clientTick = buf.ReadU32();
    }
};

struct PingResponse {
    uint32_t serverTick = 0;
    uint32_t echoClientTick = 0;

    static void Write(const PingResponse& self, SerialBuffer& buf) {
        buf.WriteU32(self.serverTick);
        buf.WriteU32(self.echoClientTick);
    }

    static void Read(PingResponse& self, SerialBuffer& buf) {
        self.serverTick = buf.ReadU32();
        self.echoClientTick = buf.ReadU32();
    }
};

struct Ping {};

struct SpawnPlayerRequest {
    uint32_t sceneId = 0;
    std::string playerName = {};

    static void Write(const SpawnPlayerRequest& self, SerialBuffer& buf) {
        buf.WriteU32(self.sceneId);
        buf.WriteString(self.playerName);
    }

    static void Read(SpawnPlayerRequest& self, SerialBuffer& buf) {
        self.sceneId = buf.ReadU32();
        self.playerName = buf.ReadString();
    }
};

struct SpawnPlayerResponse {
    uint32_t entityId = 0;
    bool success = false;

    static void Write(const SpawnPlayerResponse& self, SerialBuffer& buf) {
        buf.WriteU32(self.entityId);
        buf.WriteU8(self.success ? 1 : 0);
    }

    static void Read(SpawnPlayerResponse& self, SerialBuffer& buf) {
        self.entityId = buf.ReadU32();
        self.success = buf.ReadU8() != 0;
    }
};

struct SpawnPlayer {};

struct GetPlayerStatsRequest {
    uint32_t playerId = 0;

    static void Write(const GetPlayerStatsRequest& self, SerialBuffer& buf) {
        buf.WriteU32(self.playerId);
    }

    static void Read(GetPlayerStatsRequest& self, SerialBuffer& buf) {
        self.playerId = buf.ReadU32();
    }
};

struct GetPlayerStatsResponse {
    uint32_t kills = 0;
    uint32_t deaths = 0;
    uint16_t pingMs = 0;

    static void Write(const GetPlayerStatsResponse& self, SerialBuffer& buf) {
        buf.WriteU32(self.kills);
        buf.WriteU32(self.deaths);
        buf.WriteU16(self.pingMs);
    }

    static void Read(GetPlayerStatsResponse& self, SerialBuffer& buf) {
        self.kills = buf.ReadU32();
        self.deaths = buf.ReadU32();
        self.pingMs = buf.ReadU16();
    }
};

struct GetPlayerStats {};

} // namespace Elysium::Generated

namespace Elysium::Services {

template <> struct InvokeMethod<Elysium::Generated::Ping> {
    using Request  = Elysium::Generated::PingRequest;
    using Response = Elysium::Generated::PingResponse;
    static constexpr InvokeMethodId Id = 0xff;
};

template <> struct InvokeMethod<Elysium::Generated::SpawnPlayer> {
    using Request  = Elysium::Generated::SpawnPlayerRequest;
    using Response = Elysium::Generated::SpawnPlayerResponse;
    static constexpr InvokeMethodId Id = 0x1;
};

template <> struct InvokeMethod<Elysium::Generated::GetPlayerStats> {
    using Request  = Elysium::Generated::GetPlayerStatsRequest;
    using Response = Elysium::Generated::GetPlayerStatsResponse;
    static constexpr InvokeMethodId Id = 0x2;
};

} // namespace Elysium::Services